name: MapConductorSampleApp
options:
  bundleIdPrefix: com.mapconductor
  deploymentTarget:
    iOS: "17.0"

packages:
  ios-sdk-core:
    url: https://github.com/MapConductor/ios-sdk-core
    revision: 9c419d47ad623285cff8b2d1b870c59bff5f8567
  ios-for-mapkit:
    url: https://github.com/MapConductor/ios-for-mapkit
    revision: efb1dd50262964ff7836f0c8e11b7700b4a019bf
  ios-for-maplibre:
    url: https://github.com/MapConductor/ios-for-maplibre
    revision: 45761bb5c19f89a5e806427d16394c5af9decf2b
  ios-for-googlemaps:
    url: https://github.com/MapConductor/ios-for-googlemaps
    revision: 524c3c70e45406b734cc1a57612773ed88b63d81
  ios-heatmap:
    url: https://github.com/MapConductor/ios-heatmap
    revision: f87531a5311ad6a8f1f6d08ce9ae9d2086adea67
  ios-marker-cluster:
    url: https://github.com/MapConductor/ios-marker-cluster
    revision: b923daccd4876ae571d628da7a1fc04ea0508443
  ios-maps-sdk:
    url: https://github.com/googlemaps/ios-maps-sdk
    version: 10.7.0

targets:
  MapConductorSampleApp:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources/Assets.xcassets
    postBuildScripts:
      - name: Copy Sample PNG Resources
        script: |
          set -euo pipefail
          RES_DIR="${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
          mkdir -p "${RES_DIR}"
          for ext in png jpg jpeg; do
            for dir in "${SRCROOT}/Resources" "${SRCROOT}/.."; do
              for file in "${dir}/"*.${ext}; do
                if [ -e "${file}" ]; then
                  cp -f "${file}" "${RES_DIR}/"
                fi
              done
            done
          done
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.mapconductor.sample
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "Apple Development"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Release:
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          COPY_PHASE_STRIP: NO
          STRIP_INSTALLED_PRODUCT: YES
    configFiles:
      Debug: Config/Secrets.xcconfig
      Release: Config/Secrets.xcconfig
    dependencies:
      - package: ios-sdk-core
        product: MapConductorCore
      - package: ios-for-googlemaps
        product: MapConductorForGoogleMaps
      - package: ios-for-maplibre
        product: MapConductorForMapLibre
      - package: ios-for-mapkit
        product: MapConductorForMapKit
      - package: ios-heatmap
        product: MapConductorHeatmap
      - package: ios-marker-cluster
        product: MapConductorMarkerCluster
      - package: ios-maps-sdk
        product: GoogleMaps

schemes:
  MapConductorSampleApp:
    build:
      targets:
        MapConductorSampleApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
