name: MapConductorSampleApp
options:
  bundleIdPrefix: com.mapconductor
  deploymentTarget:
    iOS: "17.0"

packages:
  mapconductor-ios-sdk:
    path: ../..
  ios-maps-sdk:
    url: https://github.com/googlemaps/ios-maps-sdk
    version: 10.7.0

targets:
  MapConductorSampleApp:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - path: Resources
        type: folder
    postBuildScripts:
      - name: Copy Sample PNG Resources
        script: |
          set -euo pipefail
          RES_DIR="${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
          mkdir -p "${RES_DIR}"
          cp -f "${SRCROOT}/Resources/"*.png "${RES_DIR}/"
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.mapconductor.sample
      configFiles:
        Debug: Config/Secrets.xcconfig
        Release: Config/Secrets.xcconfig
    dependencies:
      - package: mapconductor-ios-sdk
        product: MapConductorCore
      - package: mapconductor-ios-sdk
        product: MapConductorForGoogleMaps
      - package: mapconductor-ios-sdk
        product: MapConductorForMapLibre
      - package: mapconductor-ios-sdk
        product: MapConductorHeatmap
      - package: mapconductor-ios-sdk
        product: MapConductorMarkerClustering
      - package: ios-maps-sdk
        product: GoogleMaps

schemes:
  MapConductorSampleApp:
    build:
      targets:
        MapConductorSampleApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
